/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Datos.Pais;
import Datos.Proveedor;
import Datos.Provincia;

/**
 *
 * @author fernando guiñazú
 */
public class FormProveedor extends javax.swing.JFrame {

    /**
     * Creates new form FormProveedor
     */
    public FormProveedor() {
        initComponents();
        
        ControlForm control = new ControlForm();
        Proveedor prov = new Proveedor();
        comboPais.setModel(control.cargarComboPais());
        tablaProv.setModel(control.cargarTabla("", prov));
        
        control.ocultarColumnas(3, tablaProv);
        look();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProv = new javax.swing.JTable();
        dato = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        eliminarProv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreprov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        razonsocprov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cuitprov = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mailprov = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telprov = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        comboProvincia = new javax.swing.JComboBox();
        insertarProv = new javax.swing.JButton();
        modificarProv = new javax.swing.JButton();
        crudPais = new javax.swing.JButton();
        crudProvincia = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tablaProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProv);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        eliminarProv.setText("Eliminar Proveedor");
        eliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProvActionPerformed(evt);
            }
        });

        jLabel1.setText("Busqueda");

        jLabel2.setText("Nombre");

        jLabel3.setText("Razon Social");

        jLabel4.setText("CUIT");

        jLabel5.setText("Mail");

        jLabel6.setText("Telefono");

        jLabel7.setText("Pais");

        comboPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaisItemStateChanged(evt);
            }
        });

        jLabel8.setText("Provincia");

        comboProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        insertarProv.setText("Alta");
        insertarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarProvActionPerformed(evt);
            }
        });

        modificarProv.setText("modificar");
        modificarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProvActionPerformed(evt);
            }
        });

        crudPais.setText("otro pais");
        crudPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudPaisActionPerformed(evt);
            }
        });

        crudProvincia.setText("otra provincia");
        crudProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombreprov, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(cuitprov))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(razonsocprov, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarProv))
                            .addComponent(mailprov, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(crudPais, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modificarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboProvincia, 0, 210, Short.MAX_VALUE)
                                    .addComponent(telprov)
                                    .addComponent(comboPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(crudProvincia)
                                .addGap(18, 18, 18)
                                .addComponent(insertarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(eliminarProv)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(razonsocprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cuitprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mailprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modificarProv)
                        .addComponent(crudPais)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(insertarProv)
                    .addComponent(crudProvincia))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Pais pais       = new Pais();
       ControlForm control = new ControlForm();
       
       pais = (Pais) comboPais.getSelectedItem();
       comboProvincia.setModel(control.cargarComboProvincia(pais.getId()));
       
    }//GEN-LAST:event_formWindowActivated

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        ControlForm control = new ControlForm();
        Proveedor prov = new Proveedor();
        tablaProv.setModel(control.cargarTabla(dato.getText(),prov));
        control.ocultarColumnas(3, tablaProv);
        dato.setText("");
       
    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProvActionPerformed
        ControlForm control = new ControlForm();
        Proveedor prov      = new Proveedor();
        
        int fila = tablaProv.getSelectedRow();
        int idprov = Integer.parseInt(tablaProv.getValueAt(fila,0).toString());
        prov.eliminar(idprov);
        tablaProv.setModel(control.cargarTabla("", prov));
        
        control.ocultarColumnas(3, tablaProv);
       
        
    }//GEN-LAST:event_eliminarProvActionPerformed

    private void insertarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarProvActionPerformed
        String nombre = nombreprov.getText();
        String razon  = razonsocprov.getText();
        String cuit   = cuitprov.getText();
        String mail   = mailprov.getText();
        String telef  = telprov.getText();
        
        ControlForm control = new ControlForm();
        Provincia provi = (Provincia) comboProvincia.getSelectedItem();
        Proveedor prove = new Proveedor();
        
        prove.insertar(nombre, razon, cuit, telef, mail, provi.getId());
        tablaProv.setModel(control.cargarTabla("",prove));
        control.ocultarColumnas(3, tablaProv);
        
        nombreprov.setText("");
        razonsocprov.setText("");
        cuitprov.setText("");
        mailprov.setText("");
        telprov.setText("");
        comboPais.setSelectedIndex(0);
        comboProvincia.setSelectedIndex(0);
        
        
       
    }//GEN-LAST:event_insertarProvActionPerformed

    private void modificarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProvActionPerformed
        int fila = tablaProv.getSelectedRow();
        int idprov = Integer.parseInt(tablaProv.getValueAt(fila,0).toString());
        String nombre = nombreprov.getText();
        String razon  = razonsocprov.getText();
        String cuit   = cuitprov.getText();
        String mail   = mailprov.getText();
        String telef  = telprov.getText();
        
        ControlForm control = new ControlForm();
        Provincia provi = (Provincia) comboProvincia.getSelectedItem();
        Proveedor prove = new Proveedor();
        
        prove.modificar(nombre, razon, cuit, telef, mail, provi.getId(), idprov);
        tablaProv.setModel(control.cargarTabla("",prove));
        control.ocultarColumnas(3, tablaProv);
        
        nombreprov.setText("");
        razonsocprov.setText("");
        cuitprov.setText("");
        mailprov.setText("");
        telprov.setText("");
        comboPais.setSelectedIndex(0);
        comboProvincia.setSelectedIndex(0);
 
       
    }//GEN-LAST:event_modificarProvActionPerformed

    private void tablaProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProvMouseClicked
        
        int fila = tablaProv.getSelectedRow();
        
        String nombre = tablaProv.getValueAt(fila,3).toString();
        String razon  = tablaProv.getValueAt(fila,4).toString();
        String cuit   = tablaProv.getValueAt(fila,5).toString();
        String mail   = tablaProv.getValueAt(fila,6).toString();
        String telef  = tablaProv.getValueAt(fila,7).toString();
        nombreprov.setText(nombre);
        razonsocprov.setText(razon);
        cuitprov.setText(cuit);
        mailprov.setText(mail);
        telprov.setText(telef);
        
        int idpais = Integer.parseInt(tablaProv.getValueAt(fila,2).toString());
        int idprov = Integer.parseInt(tablaProv.getValueAt(fila,1).toString());
        String nompais = tablaProv.getValueAt(fila,9).toString();
        String nomprov = tablaProv.getValueAt(fila,8).toString();
        
        Pais pais = new Pais(idpais,nompais);
        Provincia prov = new Provincia(idprov,nomprov);
        comboPais.getModel().setSelectedItem(pais);
        comboProvincia.getModel().setSelectedItem(prov);
        
    }//GEN-LAST:event_tablaProvMouseClicked

    private void comboPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaisItemStateChanged
        ControlForm control = new ControlForm();
        Pais pais = (Pais) comboPais.getSelectedItem();
        comboProvincia.setModel(control.cargarComboProvincia(pais.getId()));
    }//GEN-LAST:event_comboPaisItemStateChanged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        nombreprov.setText("");
        razonsocprov.setText("");
        cuitprov.setText("");
        mailprov.setText("");
        telprov.setText("");
        comboPais.setSelectedIndex(0);
        comboProvincia.setSelectedIndex(0);
    }//GEN-LAST:event_formMouseClicked

    private void crudPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudPaisActionPerformed
        FormPais fpais = new FormPais();
        fpais.setVisible(true);
    }//GEN-LAST:event_crudPaisActionPerformed

    private void crudProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudProvinciaActionPerformed
        FormProvincia fprov = new FormProvincia();
        fprov.setVisible(true);
        
    }//GEN-LAST:event_crudProvinciaActionPerformed

    public static void look() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox comboPais;
    private javax.swing.JComboBox comboProvincia;
    private javax.swing.JButton crudPais;
    private javax.swing.JButton crudProvincia;
    private javax.swing.JTextField cuitprov;
    private javax.swing.JTextField dato;
    private javax.swing.JButton eliminarProv;
    private javax.swing.JButton insertarProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mailprov;
    private javax.swing.JButton modificarProv;
    private javax.swing.JTextField nombreprov;
    private javax.swing.JTextField razonsocprov;
    private javax.swing.JTable tablaProv;
    private javax.swing.JTextField telprov;
    // End of variables declaration//GEN-END:variables
}
