/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Datos.MySQLConnect;
import Datos.Ciudad;
import Datos.Cliente;
import Datos.Pais;
import Datos.Provincia;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fernando guiñazú
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
        look();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        nombrecli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edadcli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numdoccli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboProvincia = new javax.swing.JComboBox();
        insertarCliente = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        crudPais = new javax.swing.JButton();
        crudProvincia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboCiudad = new javax.swing.JComboBox();
        crudCiudad = new javax.swing.JButton();
        realizarReporteCompleto = new javax.swing.JButton();
        realizarReporteUnico = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nombre");

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        jLabel2.setText("Edad");

        jLabel3.setText("Documento");

        jLabel4.setText("Pais");

        comboPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaisItemStateChanged(evt);
            }
        });

        jLabel5.setText("Provincia");

        comboProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProvinciaItemStateChanged(evt);
            }
        });

        insertarCliente.setText("Alta cliente");
        insertarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarClienteActionPerformed(evt);
            }
        });

        modificar.setText("Modificar Cliente");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        crudPais.setText("Crud pais");
        crudPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudPaisActionPerformed(evt);
            }
        });

        crudProvincia.setText("Crud Provincia");
        crudProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudProvinciaActionPerformed(evt);
            }
        });

        jLabel6.setText("Busqueda");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel7.setText("Ciudad");

        comboCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        crudCiudad.setText("Crud Ciudad");
        crudCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudCiudadActionPerformed(evt);
            }
        });

        realizarReporteCompleto.setText("Reporte Completo");
        realizarReporteCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarReporteCompletoActionPerformed(evt);
            }
        });

        realizarReporteUnico.setText("Reporte Unico");
        realizarReporteUnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarReporteUnicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(insertarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(buscar)
                                    .addGap(18, 18, 18)
                                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                            .addComponent(numdoccli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel7))
                                                    .addGap(39, 39, 39))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(comboProvincia, 0, 107, Short.MAX_VALUE)
                                                .addComponent(comboPais, 0, 107, Short.MAX_VALUE)
                                                .addComponent(comboCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(crudPais, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(crudCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(crudProvincia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                                            .addGap(38, 38, 38))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(edadcli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(realizarReporteCompleto)
                                .addGap(18, 18, 18)
                                .addComponent(realizarReporteUnico, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realizarReporteCompleto)
                    .addComponent(realizarReporteUnico))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(edadcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numdoccli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crudPais)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crudProvincia)
                    .addComponent(comboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crudCiudad)
                    .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(insertarCliente))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarClienteActionPerformed
        Cliente cli = new Cliente();
        ControlForm control = new ControlForm();
        
        String nombre  = nombrecli.getText();
        int edad       = Integer.parseInt(edadcli.getText());
        String numdoc  = numdoccli.getText();
        Provincia prov = (Provincia) comboProvincia.getSelectedItem();
        
        cli.insertar(nombre, edad, numdoc, prov.getId());
        tablaCliente.setModel(control.cargarTabla("",cli));
        control.ocultarColumnas(4, tablaCliente);
    }//GEN-LAST:event_insertarClienteActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        
        String datocli = dato.getText();
        Cliente cli    = new Cliente();
        
        ControlForm control = new ControlForm();
        
        tablaCliente.setModel(control.cargarTabla(datocli, cli));
        control.ocultarColumnas(4, tablaCliente);
        dato.setText("");
    }//GEN-LAST:event_buscarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ControlForm control = new ControlForm();
        comboPais.setModel(control.cargarComboPais());
        
        Pais pais = (Pais) comboPais.getSelectedItem();
        comboProvincia.setModel(control.cargarComboProvincia(pais.getId()));
        
        Provincia prov = (Provincia) comboProvincia.getSelectedItem();
        comboCiudad.setModel(control.cargarComboCiudad(prov.getId()));
        
        Cliente cli = new Cliente();
        tablaCliente.setModel(control.cargarTabla("",cli));
        control.ocultarColumnas(4, tablaCliente);
    }//GEN-LAST:event_formWindowActivated

    private void comboPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaisItemStateChanged
        Pais pais = (Pais) comboPais.getSelectedItem();
        ControlForm control = new ControlForm();
        comboProvincia.setModel(control.cargarComboProvincia(pais.getId()));
        
        Provincia prov = (Provincia) comboProvincia.getSelectedItem();
        comboCiudad.setModel(control.cargarComboCiudad(prov.getId()));
    }//GEN-LAST:event_comboPaisItemStateChanged

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Cliente cliente = new Cliente();
        ControlForm control = new ControlForm();
        int fila = tablaCliente.getSelectedRow();
        int id   = Integer.parseInt(tablaCliente.getValueAt(fila,0).toString());
        
        cliente.eliminar(id);
        tablaCliente.setModel(control.cargarTabla("",cliente));
        control.ocultarColumnas(4, tablaCliente);
    }//GEN-LAST:event_eliminarActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        int fila = tablaCliente.getSelectedRow();
        
        int idprovin  = Integer.parseInt(tablaCliente.getValueAt(fila,2).toString());
        int idpais    = Integer.parseInt(tablaCliente.getValueAt(fila, 3).toString());
        int idciudad  = Integer.parseInt(tablaCliente.getValueAt(fila,1).toString());
        
        String nomciu = tablaCliente.getValueAt(fila,7).toString();
        String provin = tablaCliente.getValueAt(fila,8).toString();
        String nompas = tablaCliente.getValueAt(fila,9).toString();
        String edad   = tablaCliente.getValueAt(fila,5).toString();
        String nombre = tablaCliente.getValueAt(fila,4).toString();
        String numdoc = tablaCliente.getValueAt(fila, 6).toString();
        
        Pais pais = new Pais(idpais,nompas);
        Provincia prov = new Provincia(idprovin,provin);
        Ciudad ciu = new Ciudad(idciudad,nomciu);
        
        nombrecli.setText(nombre);
        numdoccli.setText(numdoc);
        edadcli.setText(edad);
        comboPais.getModel().setSelectedItem(pais);
        comboProvincia.getModel().setSelectedItem(prov);
        comboCiudad.getModel().setSelectedItem(ciu);
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        ControlForm control = new ControlForm();
        Cliente cliente     = new Cliente();
        Ciudad ciu      = (Ciudad) comboCiudad.getSelectedItem();
        
        int fila = tablaCliente.getSelectedRow();
        int id   = Integer.parseInt(tablaCliente.getValueAt(fila,0).toString());
        int edad = Integer.parseInt(edadcli.getText());
        
        String nombre = nombrecli.getText();
        String numdoc = numdoccli.getText();
        int idciu  = ciu.getId();
        
        cliente.modificar(id, nombre, edad, numdoc,idciu);
        tablaCliente.setModel(control.cargarTabla("",cliente));
        control.ocultarColumnas(4, tablaCliente);
        
        System.out.println(id+nombre+edad+numdoc+idciu);
        nombrecli.setText("");
        edadcli.setText("");
        numdoccli.setText("");
        comboPais.setSelectedIndex(0);
        comboProvincia.setSelectedIndex(0);
        
    }//GEN-LAST:event_modificarActionPerformed

    private void crudPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudPaisActionPerformed
        FormPais fpais = new FormPais();
        fpais.setVisible(true);
    }//GEN-LAST:event_crudPaisActionPerformed

    private void crudProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudProvinciaActionPerformed
        FormProvincia fprov = new FormProvincia();
        fprov.setVisible(true);
    }//GEN-LAST:event_crudProvinciaActionPerformed

    private void comboProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProvinciaItemStateChanged
        ControlForm cformu = new ControlForm();
        Provincia prov = (Provincia) comboProvincia.getSelectedItem();
        
        comboCiudad.setModel(cformu.cargarComboCiudad(prov.getId()));
        
    }//GEN-LAST:event_comboProvinciaItemStateChanged

    private void crudCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudCiudadActionPerformed
         FormCiudad fciu = new FormCiudad();
         fciu.setVisible(true);
    }//GEN-LAST:event_crudCiudadActionPerformed

    private void realizarReporteCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarReporteCompletoActionPerformed
        try {
             MySQLConnect con = new MySQLConnect();
             String dir = "C:\\Users\\luciano\\Documents\\NetBeansProjects\\NuevoProDos\\src\\Aplicacion\\ReporteCompletoCliente.jrxml";
             
             JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
             JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, con.conexionBD());
             JasperViewer JV = new JasperViewer(mostrarReporte,false);
             JV.setVisible(true);
             
         } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);} 
        
        
    }//GEN-LAST:event_realizarReporteCompletoActionPerformed

    private void realizarReporteUnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarReporteUnicoActionPerformed
         try {
             Map parametro = new HashMap();
             String ciudad = JOptionPane.showInputDialog("ingrese la ciudad");
             parametro.put("nombre" , ciudad);
          
             MySQLConnect con = new MySQLConnect();
             String dir = "C:\\Users\\luciano\\Documents\\NetBeansProjects\\NuevoProDos\\src\\Aplicacion\\ReporteUnico.jrxml";
             
             JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
             JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, parametro, con.conexionBD());
             JasperViewer JV = new JasperViewer(mostrarReporte,false);
             JV.setVisible(true);
             
             
         } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);} 
    }//GEN-LAST:event_realizarReporteUnicoActionPerformed

    public static void look() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox comboCiudad;
    private javax.swing.JComboBox comboPais;
    private javax.swing.JComboBox comboProvincia;
    private javax.swing.JButton crudCiudad;
    private javax.swing.JButton crudPais;
    private javax.swing.JButton crudProvincia;
    private javax.swing.JTextField dato;
    private javax.swing.JTextField edadcli;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton insertarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombrecli;
    private javax.swing.JTextField numdoccli;
    private javax.swing.JButton realizarReporteCompleto;
    private javax.swing.JButton realizarReporteUnico;
    private javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables
}
