/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;
/**
 *
 * @author fernando guiñazú
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        look();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPaises = new javax.swing.JButton();
        formProv = new javax.swing.JButton();
        formProveedor = new javax.swing.JButton();
        formCliente = new javax.swing.JButton();
        formCiud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formPaises.setText("ABM Paises");
        formPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPaisesActionPerformed(evt);
            }
        });

        formProv.setText("ABM Provincias");
        formProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formProvActionPerformed(evt);
            }
        });

        formProveedor.setText("ABM Proveedores");
        formProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formProveedorActionPerformed(evt);
            }
        });

        formCliente.setText("ABM Clientes");
        formCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formClienteActionPerformed(evt);
            }
        });

        formCiud.setText("AMB Ciudades");
        formCiud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCiudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formPaises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formCiud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(formPaises)
                .addGap(18, 18, 18)
                .addComponent(formProv)
                .addGap(18, 18, 18)
                .addComponent(formProveedor)
                .addGap(18, 18, 18)
                .addComponent(formCliente)
                .addGap(18, 18, 18)
                .addComponent(formCiud)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPaisesActionPerformed
        FormPais fpais = new FormPais();
        fpais.setVisible(true);
    }//GEN-LAST:event_formPaisesActionPerformed

    private void formProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formProvActionPerformed
        FormProvincia fprov = new FormProvincia();
        fprov.setVisible(true);
    }//GEN-LAST:event_formProvActionPerformed

    private void formProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formProveedorActionPerformed
        FormProveedor fprove = new FormProveedor();
        fprove.setVisible(true);
    }//GEN-LAST:event_formProveedorActionPerformed

    private void formClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formClienteActionPerformed
        FormCliente cli = new FormCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_formClienteActionPerformed

    private void formCiudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCiudActionPerformed
        FormCiudad fciu = new FormCiudad();
        fciu.setVisible(true);
    }//GEN-LAST:event_formCiudActionPerformed

    public static void look() {        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton formCiud;
    private javax.swing.JButton formCliente;
    private javax.swing.JButton formPaises;
    private javax.swing.JButton formProv;
    private javax.swing.JButton formProveedor;
    // End of variables declaration//GEN-END:variables
}
